src/Widgets/ListFooter.vala

* Subclass ActionBar instead of Toolbar
* Use GObject-style construction
* remove unnecessary properties
* Connect signals at the end
* Cuddle else

ListFooter.vala: rewrite as ActionBar in GObject style

---

cli/GuestSessionToggle.vala

LightDM enables the guest session by default if no configuration option is present. A previous commit changed the default value in the `guest-session-toggle CLI` to false. This PR reverts that change.
Fixes #24.

Guest session is enabled by default

---

src/Widgets/ListFooter.vala

This attempts to sort out some gross spaghetti with deciding the sensitivity state of add and remove buttons.
Firstly, we check if we have permission. If we don't have permission, set insensitive and GTFO. There's no point doing all this other stuff if we can't actually do any stuff.
Then we check if the selected user is `null`. This basically means it's the guest account. We do this first because it's cheap: we're only checking one thing.
If the selected user is not the guest, we check to make sure that it isn't ourselves, the last admin on the system, or... they have an auto login I guess? I'm not really sure why that's there. But hey we'll keep it because whatever. As long as the selected user isn't one of those things, they can be removed.
If the selected user is one of these things, …

ListFooter.vala: Sort out conditional spaghetti

---

src/Misc/Utils.vala

Fixes #2 
If we drop a string down to ASCII before iterating through the UTF-8 array, all of the accented characters get converted to their nearest ASCII equivalent.

Convert fullname to ascii for generated username

---

src/Widgets/PasswordEditor.vala

* Remove extra spaces
* Reduce scope of error_pw_label
* Use Vala-style properties

PasswordEditor.vala: Code style fixes

---

src/Widgets/Popovers/NewUserPopover.vala

* Fix spacing
* Make `request_user_creation` legible
* Remove unnecessary haligns and width requests
* Vala-style properties
* Connect signals at the end
* Rework a bit of logic in `check_input ()` and cache `username_entry`'s text

NewUserPopover.vala: Code style fixes

---

src/CMakeLists.txt
src/Dialogs/NewUserDialog.vala
src/Widgets/ErrorRevealer.vala
src/Widgets/PasswordEditor.vala

There's definitely a lot more work here to be done as far as de-duplicating things between the new user dialog and change password popover, but here is one step

Move ErrorRevealer to its own class

---

src/Dialogs/ChangePasswordDialog.vala

If this button is sensitive (aka clickable) then `pw_editor.is_valid`. So it doesn't make sense to check this when it must be true

ChangePasswordDialog: remove redundant check

---

src/Dialogs/NewUserDialog.vala
src/Widgets/PasswordEditor.vala

This changes PasswordEditor to be a little bit more like the password validation from NewUserDialog. It isn't meant to be a complete port, just one step closer in a series of small PRs
* Fixes out of order widget and extra widget in NewUserDialog
* Uses a revealer for confirm entry error messages
* Add header labels for entries instead of placeholder text
* Renames lots of variable names to be the same
* Set the grid orientation to vertical and use `add`
* Use settings bindings for show password check
* Don't use tooltips to communicate errors or warnings

PasswordEditor: copy layout from NewUserDialog

---

src/Dialogs/ChangePasswordDialog.vala
src/Widgets/PasswordEditor.vala

After this, it should be possible to make NewUserDialog use the password editor widget

Use the new validation from NewUserDialog

---

src/Dialogs/NewUserDialog.vala
src/Widgets/PasswordEditor.vala

Uses `process-error-symbolic` instead of `dialog-error-symbolic` which matches better with `process-completed-symbolic`

Use process-error-symbolic

---

src/Plug.vala
src/Views/UserSettingsView.vala

Releases privileges if updating current user's password and updates infobar visibility logic
Fixes #15

Always update current user's keyring

---

src/Widgets/UserItem.vala

In the vein of #110, only setting things which have actually changed

UserItem: bind username change to its own property

---

cli/meson.build
data/meson.build
meson.build
src/meson.build

On NixOS all packages are installed into their own immutable prefix.
Because of this switchboard_dep.get_pkgconfig_variable will return a
path from within switchboard's prefix and we cannot write to it.
By using define_variable we can replace the libdir to be from the
paths from meson. This should have no affect on elementaryOS.
---
Also includes https://github.com/elementary/switchboard-plug-useraccounts/commit/eec88f92735c952558b0e3a7a5335d281d132420 for completion.

build: fix install path for switchboard plug

---

src/Dialogs/NewUserDialog.vala

This is the same as https://github.com/elementary/initial-setup/pull/81
Prevents us getting users that are locked after creation on `focal`.~~I've tested that this also works properly on `bionic` too and all good.~~
Edit: wait, I haven't tested this on bionic, I'm an idiot.

Create user without user_added signal

---

src/Widgets/PasswordEditor.vala

Gives us a nice scale from red to green:

PasswordEditor: Adjust password levelbar values

---

src/Misc/DeltaUser.vala
src/Views/UserSettingsView.vala

Fixes #150 
It seems like maybe delta user isn't updated correctly or something. I also tried listening to `user.notify["icon-file"]` and that wasn't working so I dunno

UserSettingsView: skip checking delta user when updating avatar

---

src/Views/UserSettingsView.vala

We don't need to check for updates to name labels etc when permission changes and we don't need to set certain widget sensitivities when names change, so these are split into two separate functions so that we only do the work we need to do when we need to do it

UserSettingsView: split update_ui and update_permission

---

src/Views/UserSettingsView.vala

Since you can't change these while they're true, we don't need to update them when the user info changes

UserSettingsView: Only set current/last tooltips once

---

src/Widgets/UserItem.vala

Don't bind it, we are already updating the icon whihin the `changed` signal handler.

UserItem: The icon-file property doesn't exist anymore

---

src/Dialogs/NewUserDialog.vala
src/Widgets/PasswordEditor.vala

There's currently no way to set a validated entry to be of type "warn" instead of "error", so we can't replace the entry for choosing a password

Use Granite.ValidatedEntry

---

src/Plug.vala
src/Widgets/UserItem.vala

Fixes #155 
An alternative to #156 that also allows UserItem destruction.
* Add an extra reference before asking accountservice to delete
* Make a weak signal connection between user and avatar
In passing the deprecated Hdy.Avatar function `set_image_load_func` is replaced with `set_loadable_icon`

Fix crash after deleting a newly added user; ensure UserItem destruct

---

src/meson.build

HdyAvatar loadable-icon property was added in version 1.1.90:
https://gitlab.gnome.org/GNOME/libhandy/-/blob/master/NEWS#L82

meson: require libhandy-1 >= 1.1.90

---

src/Misc/Utils.vala
src/Views/UserSettingsView.vala

Basically the same as: https://github.com/elementary/switchboard-plug-locale/pull/138
This means the following:
* We stop relying on the Ubuntu specific way of getting available languages
* We use a GNOME method to parse locales instead of hardcoded length based string slices, which don't work for 3 letter locales
* We optimize some loops by not looking up the user's language for every language installed on the system
* We correctly fall back to the system locale if a user doesn't have a specific locale set (as per the accountsservice spec)
* Just generally do a better job of error handling on operating systems that aren't Ubuntu based

Utils: Replace usage of language-options

---

src/run-passwd.c
src/run-passwd.h

This is a direct copy and paste from `gnome-control-center`, so lets update it from there.
Couple of useful bits of cleanup here and two bug fixes:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/commit/7cbccd357814a6c0f2a8574d0f8b49da9e581b43
https://gitlab.gnome.org/GNOME/gnome-control-center/-/commit/65d3b71d98694055d4868dfa9e725203ab413619

Update run-passwd from g-c-c

---

src/Misc/Utils.vala
src/Widgets/UserListBox.vala

Instead of relying on a hardcoded Ubuntu path for detecting which display manager is in use, ask systemd what it's launching in the first instance, then fallback to the old way if that's not available.
Additionally guard execution of the `guest-session-toggle` binary with the display manager check as it's LightDM specific and produces a load of log spam if LightDM isn't available.

Use systemd to detect display manager

---

src/Misc/InfobarNotifier.vala
src/Misc/UserUtils.vala
src/Plug.vala
src/Views/UserSettingsView.vala

Instead of throwing an Infobar if we fail to set change the current user's password, throw a message dialog instead.
While we're here, move `change_password` to `UserSettingsView` since that's the only place it's used and we can call `get_toplevel` if the function is inside a Gtk.Widget

Replace InfobarError with MessageDialog

---

src/Dialogs/AvatarDialog.vala
src/Widgets/CropView.vala
src/Widgets/Popovers/AvatarPopover.vala

This fixes #114, where the selected image is not rotated correctly.
I had to use the synchronous API to read the file to a Pixbuf and to apply the orientation to the image. Since the AsyncImage was removed from Granite sometime last year, and since we are only reading one image file at a time, I don’t think this will cause a great performance problem.
I used this opportunity to make the default selection (which was 50% linear dimension and at the top-left corner) a bit more universally useful at 75% linear dimension and in the center of the image. See the example images above.
I have also used this opportunity to clean up some of the code that creates the CropView, I hope that is all right.
The changes are best reviewed per-commit.
If you need me to make any changes, please let me know.

Fix avatar rotation

---

src/Views/UserSettingsView.vala

This resolves #144; makes sure that the Real Name does not start or end with whitespace.

Strip whitespace around Real Name when editing

---

src/Views/MainView.vala
src/Views/UserSettingsView.vala

Makes a "Create a new user" button bigger by putting "Remove user" button inside each user's page.

Use new listbox pattern

---

src/Views/MainView.vala

All other such buttons use title case.

Use title case for "Create User Account…"

---

src/Widgets/ErrorRevealer.vala

- Don't derive from `Gtk.Revealer` 
- construct with properties
- Some cleanup like not storing the label property as it's not used anywhere
- Don't set the label property in the Object call as that required a `null` check on the label widget

ErrorRevealer: GTK4 preparations

---

data/useraccounts.policy.in.in
src/Plug.vala

Same fix with https://github.com/elementary/switchboard-plug-locale/pull/162 but we embeded the same message in the plug domain thus the message in the polkit dialog is shown as translated as expected.
However, it is better to keep the message only in the policy file for maintainability.

policy: Do not specify the gettext-domain

---

src/Views/UserSettingsView.vala

* Pretend to be a simplesettingspage
* Create an action area separate from the content area and put buttons there
* Reduce the number of lock buttons
* Remove the word "User" from button labels since it can be inferred from the context that these buttons affect this page

UserSettingsView: create action area

---

src/Views/MainView.vala
src/Views/UserSettingsView.vala

Gotta get the infobar off the top of the window for window controls

UserSettingsView: move infobar here

---

src/Views/UserSettingsView.vala

Really tiny thing but make sure to use the correct user-facing name.
https://github.com/elementary/switchboard-plug-locale/blob/23d3695b030dc846351eebbbe86197b9dbcd2969/data/locale.metainfo.xml.in#L10

UserSettingsView: Correct display name of Locale plug

---

src/Views/UserSettingsView.vala

Closes #232 
* Layout contents vertically. Fits in with modern layouts in other panes
* Use secondary text for explanations instead of tooltip text on locks which can't really be read easily on touch
* Set mnemonic widgets

UserSettingsView: layout vertically, remove lock images

---

meson.build

This fixes the plug is always shown in English regardless of user language in OS 8.0 Daily

meson: Correct GETTEXT_PACKAGE

---

data/meson.build
meson.build
po/extra/meson.build
po/meson.build

Now it requires meson >= 0.58.0 because of `varname` positional argument of `get_variable()`:
https://mesonbuild.com/Reference-manual_returned_dep.html#arguments5

meson: Fix deprecations

---

src/Views/UserSettingsView.vala

Fixes a small visual bug where box shadow is cut off for the region dropdown

UserSettingsView: set region revealer overflow visible
