elementary/switchboard-plug-useraccounts

src/Plug.vala

* Code style
* Remove unnecessary casts
* Group main_grid methods
* Use built-in Infobar.visible

Cleanup plug.vala

---

src/Views/GuestSettingsView.vala

* Use GObject-style construction
* Code style
* Remove unnecessary casts
* Use Gtk.CSS to style label instead of Pango

Clean up GuestSettingsView.vala

---

src/Views/UserSettingsView.vala

Use GObject-style construction

UserSettingsView.vala: GObject style

---

src/Views/UserSettingsView.vala

* Constants are UPPERCASE
* Group attach methods
* Remove unnecessary size request
* Only get bools once
* brackets on if statements

Usersettings code style

---

src/Views/MainView.vala

* Use GObject-style construction
* Reduce variable scope
* Grid not box
* Code style

MainView.vala: GObject-style

---

src/Widgets/UserItem.vala

* GObject-style construction
* Code style
* Reduce variable scope

UserItem.vala: GObject-style

---

src/Views/UserSettingsView.vala
src/Widgets/PasswordEditor.vala

* GObject-style construct
* Code style
* Group attach methods

PasswordEditor.vala: GObject-style

---

src/Widgets/PasswordEditor.vala

* Still allow admins to bypass the advice, but always give them password feedback from pwquality
* Code syle

Always give password advice

---

src/Views/UserSettingsView.vala

Fixes https://github.com/elementary/stylesheet/issues/173

UserSettingsView.vala: Center valign full name entry

---

src/Widgets/Popovers/NewUserPopover.vala

Looks like this was accidentally removed somewhere

Re-add code that sets new user password

---

src/Dialogs/NewUserDialog.vala
src/Widgets/PasswordEditor.vala

And now the circle is complete! My (technical) debts are repaid, and I am a free man.

Use PasswordEditor in NewUserDialog

---

src/Views/UserSettingsView.vala

Explicitly label change password button

---

src/Dialogs/NewUserDialog.vala
src/Widgets/PasswordEditor.vala

NewUserDialog: set default button

---

src/Dialogs/ChangePasswordDialog.vala

Fixes #65 
Sets working and error state icons

ChangePasswordDialog: better auth feedback

---

data/meson.build
meson.build

i am sorry
I'm sorry to write it separately because I am writing online

fix gues account

---

src/Misc/DeltaUser.vala
src/Misc/Utils.vala
src/meson.build

One class per file.
GObject-style while we're here

Add DeltaUser class

---

cli/GuestSessionToggle.vala

So uhhh, aside from messing with a load of whitespace, does this fix this guest session? I can't reproduce that issue on my machine.

Update guest keyfile group name

---

src/Dialogs/NewUserDialog.vala
src/Misc/Utils.vala

Move create_new_user () to the one place it's used

---

src/Misc/Utils.vala

Supposed fixes #91 
Thanks to @Dirli on Gentoo

Utils: Fix getting current user on other distros

---

src/Misc/Utils.vala
src/Widgets/UserListBox.vala

Move get_display_manager to UserListBox

---

src/Dialogs/AvatarDialog.vala

Also uses the card and checkerboard classes so we get a nice background on transparent images

AvatarDialog: Rewrite as Granite.MessageDialog

---

src/Widgets/UserItem.vala

Show in sidebar if an account is disabled

---

src/Widgets/UserItem.vala

Wanna move toward only updating the properties that have actually changed

UserItem: bind realname property

---

src/Widgets/UserItem.vala

UserItem: Bind user iconfile to property

---

src/Widgets/UserItem.vala

No more update UI method, we only set things when they change

UserItem: Use a revealer for admin label and bind property

---

cli/GuestSessionToggle.vala
src/Plug.vala

I've added 1 disabler comment, because i'm not sure changing `policy_message` is a safe change.

lint project with vala-lint

---

src/Views/UserSettingsView.vala

* Remove a couple single-use methods
* Cache `get`s
* Code style cleanup
* Re-add destructive action class when necessary

UserSettingsView: Cache some gets and cleanup

---

src/Misc/InfobarNotifier.vala
src/Misc/UserUtils.vala
src/Plug.vala
src/Views/GuestSettingsView.vala
src/Views/UserSettingsView.vala

* Vastly simplify InfobarNotifier
* Animate infobar_reboot

InfobarNotifier: Use only properties

---

data/useraccounts.appdata.xml.in

For better display in Feedback and AppCenter

AppData: Add "Settings" to name

---

.github/workflows/main.yml
.github/workflows/release.yml
README.md
src/Misc/UserUtils.vala
src/Views/UserSettingsView.vala
src/Widgets/UserItem.vala
src/Widgets/UserListBox.vala
src/meson.build

Replace Granite.Avatar with Hdy.Avatar

---

src/Misc/UserUtils.vala
src/Views/UserSettingsView.vala
src/Widgets/Popovers/AvatarPopover.vala

Also:
* move change_avatar method here since it's the only place it's used
* Use modelbuttons
* Code style
* Bump copyright

AvatarPopover: Ask for permission when needed

---

src/Views/UserSettingsView.vala

UserSettingsView: Update code style

---

src/Views/MainView.vala
src/Widgets/ListFooter.vala

Undo Toast: Use username and avoid double negative

---

meson.build
src/Plug.vala
src/config.vala.in

Provides the directory where the locales are actually installed.

l10n: Correctly setup the locales

---

src/Widgets/UserItem.vala

Looking at the [code for accountsservice](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/blob/master/src/libaccountsservice/act-user.c), there isn't any code that would cause a notify when any of these properties change, meaning the sidebar was never updated when you changed any of the properties of the user or things were changed externally.

UserItem: Don't use bind_property with accountsservice

---

data/useraccounts.appdata.xml.in

Incorporates the changes from #173 #174 #175 and #176
Feel free to improve copy as necessary

AppData updates

---

data/useraccounts.appdata.xml.in
src/Views/UserSettingsView.vala

Sorry for poor image quality.
**Before:**
**After:**

Update permissions after account changes

---

src/Views/MainView.vala

Review with hide whitespace changes
* Bump copyright
* Code style
* Box instead of grid
* child property

MainView: GTK4 prep

---

src/Dialogs/ChangePasswordDialog.vala

- Bump copyright header
- Code style
- input purpose
- Box instead of Grid
- Let dialog be resized
- Get rid of extra margins

ChangePasswordDialog: GTK 4 Prep

---

src/Dialogs/NewUserDialog.vala

* Bump copyright header
* input purpose
* Box instead of Grid
* Let dialog be resized
* Get rid of extra margins

NewUserDialog: GTK 4 prep, code style

---

src/Views/MainView.vala

* Build add_button in GTK4 friendly way and make sure orca can still read it
* actionbar.pack_start
* message dialog present, not run

MainView: more GTK4 prep

---

src/Views/MainView.vala

MainView: Don't subclass Paned

---

src/Dialogs/AvatarDialog.vala
src/Widgets/CropView.vala

No EventBox in GTK 4, so subclass DrawingArea and use EventControllers. Review with "hide whitespace"
* Update copyright header
* Remove dead code
* Explicit scope
* Gobject style

CropView: subclass DrawingArea

---

src/Views/GuestSettingsView.vala
src/Views/UserSettingsView.vala

This was fewer lines than I thought it would be

Add end window controls

---

src/Views/GuestSettingsView.vala
src/Views/MainView.vala
src/Views/UserSettingsView.vala
src/Widgets/UserItem.vala

Style as a SettingsSidebar and add window controls

Handle own titlebuttons

---

src/Widgets/Popovers/AvatarPopover.vala

Fixed in https://github.com/elementary/stylesheet/commit/e1b9d7ea749c9c697cfba9882285ade443b13b61

AvatarPopover: remove destructive action workaround

---

src/Views/GuestSettingsView.vala

GuestSettingsView: Set initial sensitivity of auto login switch

---

src/Views/MainView.vala

Stores the sidebar position configured by the user.

Store Sidebar Position

---

debian/control

control: Bump meson version

---

src/Widgets/UserItem.vala

Adjust lock icon size

---

README.md
src/Widgets/Popovers/AvatarPopover.vala
src/meson.build

Use Gtk.FileDialog instead of Gtk.FileChooserNative which is deprecated in GTK 4.10.

Use Gtk.FileDialog to choose avatar

---

debian/control

Control: add fprintd to runtime deps
